## Uncertainty exploration


### Sensitivity Analyses
Sensitivity analyses were conducted to evaluate model sensitivity to alternative data treatment and model specifications.

#### Data treatment sensitivities
Data treatments explored were as follows:

- Data removal (fixed life history, no recruitment estimation) 
	1. Fishery length data only (no catches)
  	2. Catch and lengths only
  	3. Catch and lengths only with Francis weighting
  	4. Catch, lengths and ages with Francis weighting
  	5. Catch length, age and indices with Francis weighting
  	6. Catch length, age and indices with Francis weighting and extra index variance
  	7. Catch length and indices with Francis weighting, estimate life history
- Data weighting
  	8. Dirichlet data-weighting
  	9. McAllister-Ianelli data weighting
  	10. No data-weighting
- Ageing error
  	11. Using ageing error from CARE exchange
- Length treatment
	12. Use option sex = 3 to maintain sex ratio in commercial data  

Likelihood values and estimates of key parameters and derived quantities from each sensitivity are available in Table \ref{tab:data_sensis}. Derived quantities relative to the reference model are provided in Figure \ref{fig:sensi-data-RE}. Time series of spawning output and relative spawning output are shown in Figures \ref{fig:sensi-data-ssb} and \ref{fig:sensi-data-depl}.

Deterministic length-based (with or without catches) models with fixed life history values view the stock scale and status to be below that of the reference model, though above the limit reference point. Bringing in the age data, while still fixing life history and not estimating recruitment, significantly raises the stock scale to above the reference model, though the stock status is similar to the reference model. Introduction of the index made little difference to the relative stock status. Estimating the life history values, even without estimating recruitment, brought the scale back in line with the reference model. The other data treatments regarding weighting did very little to change the results from the reference model


#### Model specification sensitivities
Model specifications looked at the estimation of indiviual and combinations of life history parameters, the estimation of recruitment, and the treatment of fecundity and selectivity. All scenarios match the reference model specificatins in all other aspects unless otherwised stated.

- Life history estimation
	- Fix natural mortality ($M$)
		1. Fix $M$ 
		2. Fix $M$ and $CV_old$
		3. Fix $M$, $t_0$ and $CV_old$
		4. Fix $M$, $k$, $t_0$ and $CV_old$ 
	- Fix growth parameters
		5. Fix all growth parameters
	 	6. Fix $L_{\infty}$, $k$, and $t0$
	 	7. Fix $k$, and $CV_old$
	 	8. Fix $L_{\infty}$ and $CV_old$
	 	9. Est $L_{\infty}$ for females only
	 	10. Est $L_{\infty}$ for males only
	 	11. 5 growth platoons instead of one
	- Recruitment estimation and variability ($\sigma_R$). All years are estimated with bias correction applied.
	 	12. No recruitment estimation
	 	13. No recruitment esimation and fixed life history parameters
	 	14. $\sigma_R$ = 0.45
	 	15. $\sigma_R$ = 0.75	
- Miscellaneous
	16. Fecundity proportional to weight
	17. Estimate dome-shaped selectivity
	
Likelihood values and estimates of key parameters and derived quantities from each sensitivity are available in Tables \ref{tab:modspec_LH_sensis} and \ref{tab:modspec_RecMisc_sensis}. Derived quantities relative to the reference model are provided in Figure \ref{fig:sensi-modspec-RE}. Time series of spawning output and relative spawning output are shown in Figures \ref{fig:sensi-modspec-ssb} and \ref{fig:sensi-modspec-depl}.

Fixing $M$ to the higher prior mean value while estimating $L_{\infty}$ raised both the beginning and ending stock scale and overall ending year relative stock status. Fixing growth but estimaing $M$ dropped stock scale, but preserved the stock status. Allowing either $L_{\infty}$ or $k$ to be estimated increased both stock scale and status. Fixing the life history parameters except for female $L_{\infty}$ also raised stock scale and status, though estiamating males $L_{\infty}$ made little difference to model results. Further investigation on the affect of life history values are provided in the likelihood profiles (next section).

Recruitment estimation (assuming $\sigma_R$ = 0.6) was not sensitive to a range of $\sigma_R$ values, though fixing life history values again increased both scale and relative stock status. The two remaining model specifications did little to change the reference model results.

Overall, there were no model specification sensitivity scenarios that caused the population to drop significantly below the reference model estimate of stock status, only above. When stock scale differed, unfished and current stock size offered varied similarly, with current stock size changing more, which led to increases in the relative stocks status. 


### Likelihood Profiles
Likelihood profiles were conducted for $ln(R_0)$, steepness ($h$), female and male natural mortality ($M$) values separately and varying together, female and male maximum length ($L_{\infty}$), female and male growth coefficient ($k$), female and male variability of size at maximum age. In addition, joint profiles over  $L_{\infty}$ and $k$ (that maintains a correlation structure `r round(model$cor$cormessage3[2,3],2)` between the parameters consistent with the model calculation of that correlation) were done for females and males separately. Female and male natural mortality was also covaried based on the offset in values from the reference model. Likelihood profiles were conducted by fixing the featured parameter(s) at specific values across a range of values and estimating the remaining parameters. A likelihood profile offers insight into model information on a given parameter or parameter pairing, while providing an additional way to describe uncertainty in the parameter by indentifying the range of parameters within 1.96 likelihood units of the refrence model.

The $ln(R_0)$ profiles show strong support for the maximum likelhood value of `r round(log(model$derived_quants[model$derived_quants$Label == "Recr_Virgin",2]),2)` (Figure \ref{fig:r0-profile-combo}). Population size expectedly increases as $ln(R_0)$ increases, with the increase in current biomass happening quicker than initial biomass, thus relative stock status increase towards unfished at high $ln(R_0)$ values. This is explained by the harvest rate decreasing because the removal history is fixed and becomes relatively smaller compared to the overall biomass. All data sets were mostly consistent in the information content in the profile, though the length data contained the least amount of information on $ln(R_0)$.

The steepness profile showed data supported values from 0.45 to 1, with ranges of relative stock status from 30% to 40% (Figure \ref{fig:steepness-profile-combo}). $SB_0$ showed the biggest change across steepness values, though the most informed portion of the profile did not change greatly. Length data dominated the information in the profile (Figure \ref{fig:steepness-profile-combo}). 

Natural mortality profiles for females (Figure \ref{fig:M_f-profile-combo}) and males (Figure \ref{fig:M_m-profile-combo}) highlight two important issues: 1) the inability for the data in this model to inform either of these parameters and 2) model derived values are sensitive to the value, mainly female $M$. Natural mortality values at the minimum likelihood values either goes toward unrealistically high (Figure \ref{fig:M_f-profile-combo}) or low (Figure \ref{fig:M_m-profile-combo}) $M$ values. The combined profile that varies female and male $M$ together at the same changing value behave diretionally most like the female likelihood, though with less change across values (Figure \ref{fig:M-multiprofile-combo}). Scale and relative stock status are most affected by the assumption of females rather than male $M$, as the females interact the most with the fishery.

Female growth profiles show a similar lack of information to estimate $L_{\infty}$, $k$, or CV at maximum age. Length compositions support a smaller $L_{\infty}$ when $k$ is fixed (Figure \ref{fig:Linf_F-profile-combo}) and a lower $k$ when $L_{\infty}$ is fixed (Figure \ref{fig:k_f-profile-combo}). A more realistic profile maintains the negative correlation bewtween $L_{\infty}$ and $k$ showing the lower $L_{\infty}$ value is preferred over a lower k value (Figure \ref{fig:Linf_k_f-profile}). Changing either value has a large affect on stock scale and relative stock status. The profile over the variability at maximum age supported a lower value than in the model (Figure \ref{fig:CVold_f-profile-combo}). The lower values increased overall popluation size (particularly current biomass) and derived a noticeably higher current relative stock status.

Male growth profiles showed more information and less overall sensitivity than the female profiles. Length compositions from the fishery and survey strongly supported a slightly larger $L_{\infty}$ when $k$ is fixed (Figure \ref{fig:Linf_M-profile-combo}) and a much higher $k$ when $L_{\infty}$ is fixed (Figure \ref{fig:k_m-profile-combo}), though there is essentially no information in estimating male $k$. Relative stock status changes little across $L_{\infty}$ and $k$ values, but the population scale change is more pronounced. The joint $L_{\infty}$-$k$ profile showing the higher $L_{\infty}$ value is preferred over a higher k value (Figure \ref{fig:Linf_k_m-profile}). Changing either value has a relatively small affect on stock scale and relative stock status. Overall, the influence of male growth values is smaller than females. The model supported values of the variability at maximum age between 0.1 and 0.14 (Figure \ref{fig:CVold_f-profile-combo}). Larger values decreased overall popluation size a little, with more of an affect on the more recent biomass estimates, and had only small affect on relative stock status.


### Retrospective Analysis

A ten-year retrospective analysis was conducted by running the model and sequentially removing one year of data. Retrospective spawning output estimates were gnerally within the confidence intervals of the reference model (Figure \ref{fig:retro-ssb}), which also lead to consistent estimates of stock status among the retrospective scenarios, with no strong pattern (Figure \ref{fig:retro-depl}).

