## Management 

### Reference Points

Reference points were calculated using the estimated fishery selectivity and removals in the most recent year of the model (`r endyr`, Table \ref{tab:referenceES}). Sustainable total yields  were `r round(model$derived_quants[model$derived_quants$Label == 'Dead_Catch_SPR', 'Value'], 2)` mt when using an $SPR_{50\%}$ reference harvest rate. The spawning output equivalent to 40 percent of the unfished spawning output ($SB_{40\%}$) was `r round(model$derived_quants[model$derived_quants$Label == 'SSB_SPR', 'Value'], 2)` meggs. 

The `r endyr + 1` spawning output relative to unfished equilibrium spawning output is above the `r spp` relative biomass target of 40 percent (Figure \ref{fig:depl}). The fishing intensity, $1-SPR$, of recent years was near or above the harvest rate limit ($SPR_{50\%}$) for most of the 1980s and 1990s. Recent years also show near target fishing levels (Table \ref{tab:timeseries} and Figure \ref{fig:1-spr}), highlighting how the sustainability of current fishing levels are very sensitive to incoming recruitment. Table \ref{tab:referenceES} shows the full suite of estimated reference points for the base model and Figure \ref{fig:yield} shows the equilibrium curve based on a steepness value fixed at `r round(model$parameters[model$parameters$Label == "SR_BH_steep","Value"], 2)`.

### Unresolved Problems and Major Uncertainties

Natural mortality ($M$) was estimated by the model, though vermilion rockfish longevity is not well understood in Oregon. While the estimated sex-specific $M$ values seem well within reason, the model remains sensitive to the choice of this parameter, and therefore improving the $M$ prior (the prior used in this model may be centered on the higher end) while continuing to collect age data for future estimation within the model is important. This also plays through the collection of lengths to go with ages to continue to improve the estimation of age and growth. Future work on improving point estimates and possibly investigate time-varying life history parameters could improve model fits. 

Functional maturity [@head_fxnalmatspline_2020] is an emerging concept in reproductive biology capturing physiological behaviors such as delayed maturity, skipped spawning and atresia and correcting for them in the length at maturity relationship. Investigating functional maturity could improve the application of maturity in the model.

Fishery-independent surveys would add additional support for those trends seen using fishery-based data.
 
### Harvest Projections and Decision Tables

A ten year (2023-2032) projection of the reference model with removals in 2021 and 2022 provided by the Groundfish Management Team for each fleet under the category 1 (sigma=0.5) time-varying buffer using $P^*$ = 0.45 and 40-10 ABC control rule is provided in Table \ref{tab:project}.

The decision table (Table \ref{tab:dec-tab}) was constructed using female and male natural mortality to define the low and high states of nature. The multi-parameter likelihood profile was used to find the low (Female M = 0.07092; Male M= 0.06525) and high (Female M = 0.08527; Male M = 0.07845) female and male natural mortality values that produce -log likeliehood values  +0.66 units from the reference -log likelihood value. These correspond to the 12.5% and 87.5% quantiles (standard quantiles used in west coast decision tables). The catch rows in the table were based on three proposed catch streams:

  1. P* = 0.45, sigma = 0.5
  2. P* = 0.40, sigma = 0.5
  3. An equilibrium catch based on the $F_{MSY}$ proxy using SPR = 0.5.  

Across all states of natures and catch streams vermilion relative stock size never falls below the target relative stock size of 40%. Both P* approaches lower the stock status from the high relative stock size values, while the $F_{MSY}$ proxy does not. The mismatch in the corresponding steepness value ($h=0.6$) that matches MSY at SPR = 0.5 with the steepness value in the stock assessment ($h=0.72$) that correpsonds to an MSY SPR of 0.35 explains why this constant catch will maintain the stock at very high relative stock status levels. 

### Evaluation of Scientific Uncertainty

The estimated uncertainty in the base model around the `r endyr + 1` spawning output is $\sigma$ = `r round(model$Pstar_sigma,2)` and the uncertainty in the base model around the `r endyr + 1` OFL is $\sigma$ = `r round(model$OFL_sigma,2)`. The estimated model uncertainty was less than the category 1 groundfish data moderate assessment default value of  $\sigma$ = 0.5. 

## Research and Data Needs

1. Resolution in stock structure. Continued sampling of vermilion rockfish in Oregon would allow for more genetic understanding of population structure. In addition, consideration of fishery similarities between northern California (north of Cape Menodcino) and southern Oregon may be worth further consideration to see if that is a better grouping of stocks compared to combining central and northern California.
2. Continued quantification of ageing error. The CARE exchange has high value in general to further our ability to understand the inherent variability of reading ageing structures, and should be strongly supported.
3. The life history parameters are all assumed constant through time. This assumption of stationarity is one of convenience and parsimony. Any insight into the changing of life history values or differing productivity regimes could help refine these assumptions.
4. Natural mortality proved the source of greatest uncertainty in the model. While empirical methods can help define priors for natural mortality, good sampling of age structure or direct measures (e.g., tagging) are preferred. Oregon's robust sampling program may include ways to collect data that can directly improve natural mortality estimation and reduce model uncertainty.
5. Ongoing sampling of biological data will remain a core component of information in the stock assessment and needs to be continued and supported.
6. A fishery-independent index of abundance would be a welcome inclusion in this assessment, along with the ongoing development of the ORBS index (e.g., the appropriateness of applying the Stephens-MacCall filtering method to fisheries data; how to treat months with different management measures).
7. The large uncertainty estimated in this stock assessment was limited given the asymptotic, symmetric variance estimation from the maximum likelihood estimation method. While a Bayesian model was considered and even explored for this model, it was not included due to challenges in implementation and lack of enough time to achieve a converged model. Continuted development of Bayesian approaches to characterizing uncertainty are strongly encouraged.
8. Ensemble modelling may be another potential tool to incorporate model uncertainty beyond within model variance estimation that should be considered.
9. Fishery selectivity continues to be challenging to represent, and are key parameters in the model. Blocks in selectivity and whether there are $a priori$ reasons to expect any dome-shaped selectivity deserve continued thought. The change of selectivity within a year (e.g., some seasons have depth restriction, others do not) should also be a topic of discussion.
