# Introduction
## Basic Information
This assessment reports the status of `r spp` (*Sebastes miniatus*) off the waters of Washington state using data through 2020. `r Spp` range from Prince William Sound, Alaska, to central Baja California at depths of 6 m to 436 m [@love_rockfishes_2002]. They are most commonly found from southern Oregon to Punta Baja, Mexico [@Hyde2009] at depths of 50 m to 150 m [@Hyde2009].  Hyde and Vetter [-@Hyde2009] describe an additional cryptic species related to `r spp` rockfish, the sunset rockfish (*Sebastes crocotulus*). They note that `r spp` reside in shallower depths (<100 m) compared to sunset rockfish. Sunset rockfish tend to be more southerly, and have not been reported in Oregon, so this assessment focuses only on `r spp`. Adult `r spp` tend to cluster on high relief rocky outcrops [@love_rockfishes_2002] and kelp forests [@Hyde2009]. North of Point Conception, some adults are shallower, living in caves and cracks [@love_rockfishes_2002]. Vermilion rockfish have shown high site fidelity [@Hannah2011 (only tagged 1 `r spp`); @Lea1999], and low average larval dispersal distance [@Hyde2009]. Lowe et al. [-@Lowe2009] suggested vermilion rockfish have a lower site fidelity than previously believed, but they acknowledged that their observations of movements to different depths may have been due to the reality of a shallower species and a deeper species.

The stock designation of Washington waters as a management unit was based on the observation that most of the habitat and take of `r spp` off Washington was in the very northern portion of the Washington coast, while most `r spp` in Oregon are taken off southern Oregon (Figure \ref{fig:ORWA-map}). Ninety-seven percent of `r spp` catch comes from the northern portion of Washington and ninety percent of the total mortality in Oregon is from the southern part of the state (south of Pt. Arago; Figure \ref{fig:tm-plot}). This large area of separation, low movement of larvae and adults, and the biogeographic barriers of the Columbia River outfall and lack of rocky habitat in southern Washington all support separate Washington-Oregon management units.

## Life History 
The approximate average lifespan for `r spp` rockfish is 60 years, with females living longer and growing larger than their male counterparts. 50% are mature at 5 years and about 37 cm, with males probably maturing at shorter lengths than females [@love_rockfishes_2002].

Vermilion rockfish are viviparous, and release 63,000 to 2,600,000 eggs per season. In southern California, `r spp` larvae are released between July and March. In central and northern California, this release occurs in September, December, and April-June [@love_rockfishes_2002].  In Oregon, fertilized females with ripe ovaries are encountered from April to October [@hannah_age_2012], with larval release sometime during and after that period. Larval release in fall and winter is not common among other rockfish species. Hyde and Vetter [-@Hyde2009] suggest that low larval dispersal may be due to weak poleward flow of nearshore waters corresponding with peak `r spp` larval release. 

Young-of-the-year (YOY) `r spp` settle out of the plankton during two recruitment periods per year, first from February to April and a second from August to October, and settlement has been observed in May off southern California [@love_rockfishes_2002]. There is no information on YOY settlement in Oregon. Larvae measure about 4.3 mm. Both young-of-the-year vermilion and sunset rockfish are mottled brown with areas of black, and older juveniles turn a mottled orange or red color [@Love2012a]. Juvenile fish are found individually from 6 m to 36 m, living near sand and structures. After two months, juveniles travel deeper and live on low relief rocky outcrops and other structures [@love_rockfishes_2002].

Adult `r spp` predominantly eat smaller fish, though sometimes they pursue euphausiids and other various macroplankton [@Phillips1964]. Love [-@love_rockfishes_2002] noted their diet to include octopus, salps, shrimps, and pelagic red crabs. 


## Ecosystem Considerations
This stock assessment does not explicitly incorporate trophic interactions, habitat factors or environmental factors into the assessment model, but a brief description of likely or potential ecosystem considerations are provided below. 

Vermilion rockfish feed on a wide range of both pelagic and benthic prey items, including forage fish species such as anchovies and mesopelagic fishes, squid, krill and octopus, as well as sporadically abundant
pelagic organisms such as pyrosomes, salps and pelagic red crabs [@Phillips1964; @love_rockfishes_2002]. Interestingly, other rockfishes (either juvenile or adult stages) have not been documented as prey for vermilion rockfish as they have for other larger *Sebastes* species (e.g., cowcod, bocaccio and yelloweye rockfish). Pelagic and benthic juvenile vermilion rockfish are likely preyed upon by the same wide range of predators that prey on juveniles and adults of other rockfish species, including seabirds, piscivorous fishes, and marine mammals.  

As with most other rockfish and groundfish in the California Current, recruitment, or cohort (year-class) strength appears to be highly variable for the vermilion rockfish, with only a modest apparent relationship to spawning output. Oceanographic and ecosystem factors are widely recognized to be key drivers of recruitment variability for most species of groundfish, as well as most elements of California Current food webs. Empirical estimates of recruitment from pelagic juvenile rockfish surveys have been used to inform incoming year class strength for some of these stocks, however vermilion and sunset rockfish are rarely encountered in these surveys. Specifically, only 47 of nearly 300,000 total juvenile *Sebastes* encountered in juvenile surveys since 2001 were identified as vermilion or sunset rockfish [@Field2021]. Previous studies have demonstrated that large-scale oceanographic drivers, such as the relative transport of subarctic waters (typically indicated by relative sea level) tend to relate to a substantial fraction of overall groundfish recruitment trends and ecosystem productivity [@Stachura2014, @Schroeder2019].  Although it is feasible that ecosystem factors, the results of pre-recruit surveys for co-occurring species, or the results of other groundfish assessments might ultimately be used to forecast recruitment for more data-limited stocks such as vermilion rockfish, as suggested by [@Thorson2014], such approaches would require more development and evaluation.  Consequently, environmental factors are not explicitly considered in this assessment.


## Historical and Current Fishery Information
Off the coast of Washington state, `r spp` is primarily caught in the recreational/sport fishery with very little mortality from commercial fishing (Table \ref{tab:WA_vermilion_catches}). Vermilion rockfish has been a target of recreational fishing as early as 1949 with catches varying each year from about 100 fish to over 1000 fish (in numbers) since then.

Vermilion rockfish has not been targeted by commercial fisheries in Washington waters. Washington closed state waters to commercial fixed gears in 1995 and to trawling in 1999. Off Washington, the depths preferred by vermilion rockfish are predominantly found within state waters. Washington state closed its waters in response to the development of the live-fish fishery in California and Oregon, and took preemptive action in 1999 to prevent the fishery from developing by prohibiting the landing of live-fish. At the time, rockfish were believed to be low productivity and could not support both commercial and recreational fishing pressure in state waters. There are four treaty tribes that fish under separate rules and are not subject to the state water closure; however, to date, no 'r spp' have been observed within a species composition sample at any tribal commercial offloads. `r Spp` are landed in the Nearshore Rockfish group, a mixed-species market category. Species composition samples were taken from sampled landings and proportions of `r spp` reported in the Nearshore market category would be estimated by port, quarter, gear, and year. In 2020, COVID-19 closures of tribal lands prevented samplers from accessing all commercial catch.

Examination of the WCGOP data set, 2002-2019, also shows that commercial catches of `r spp` are rare off Washington. In the individual fishing quota program--which began in 2011 and where coverage of discards is effectively 100 percent--there has been only one `r spp` catch event observed. The boat is recorded as having caught 400 lbs of `r spp` and as departing from and returning to a port in Oregon. The catch from that boat was recorded as having been retained and therefore would have been recorded on an Oregon fish ticket. WCGOP has also covered the Limited Entry Sablefish fishery since 2002. Observers recorded three catch events of `r spp` off Washington in 2002 totalling 25 lbs. Observer coverage in that fishery sector in 2002 was over 20%. Since 2002 observer coverage in that sector has ranged from 9%-52%. Only one other catch of `r spp` has been recorded off Washington. The non-trawl Rockfish Conservation Area off of Washington extends from shore to 100 fathoms and excludes the sector from core `r spp` habitats. WCGOP also covered the ocean pink trawl fishery in Washington since 2010 at coverage levels of 9%-19% and has recorded a single `r spp` catch event off Washington of 2 lbs.

The primary region of recreational fishing off the Washington coast occurs in the northern most regions. These areas have rocky habitat that rockfish species such as `r spp` rockfish are associated with in comparison to the southern coast of Washington which consists primarily of soft and sandy substrate. The stock off the Washington coast was assessed as a separate stock from other populations off the West Coast based on three factors: 1) suspected limited flow of fish between Washington and Oregon given the substrate separation, 2) the different exploitation patterns within Washington waters compared to Oregon and California, and 3) the quantity of length data in Washington compared to other areas. 


## Summary of Management History and Performance
`r Spp` is managed by the Pacific Fishery Management Council (PFMC) as a part of the Shelf Rockfish North and Shelf Rockfish South complexes. The North and South areas are split at N. 40°10’ Lat. N. off the West Coast. The complex is managed based on a complex level overfishing limit (OFL) and annual catch limit (ACL). The OFL and ACL values for the complex are determined by summing the species specific OFLs and ACLs managed within the complex. Removals for species within the Rockfish complex are managed and tracked against the complex total OFL and ACL, rather than on a species by species basis. The OFL and ACLs for `r spp` North of 40°10’ Lat. N. management area and the total removals are shown in Table \ref{tab:OR_vermilion_mgmt}. There are no state-specific allocations of this complex and so removals are evaluated at the regional level (North of 40°10’). 
