## Fishery-Dependent Data

### Recreational
#### Removals
Annual catches (Table \ref{tab:WA_vermilion_catches}) from the recreational fishery (1967, 1979-1989) were obtained from historical reports, and landings from 1990-2020 were obtained from the Washington Department of Fish and Wildlife (WDFW) Ocean Sampling Program (OSP) and Puget Sound Baseline Sampling Program. Puget Sound is not included in this assessment, as that is Washington State waters exclusively, but `r spp` is a relatively rare species in the Puget Sound and Salish Sea. Previous to 1979, the ratio of vermilion to black rockfish for years both were recorded was used to build a predictive linear relationship to fill in years of missing vermilion catches (Figure \ref{fig:WA_black_vermilion}). This choice was made to leverage the historical black rockfish catch reconstruction performed by Cope et al. [-@cope_assessments_2016], as black rockfish are the most common rockfish caught in Washington, and has an overlapping presence with vermilion. The predictive ratio was used to find landed values (in numbers of fish) between 1968 and 1979, and resulted in zero landings in 1949, thus defining the start year of the model. Because the relationship is highly variable, the mininum and maximum ratios were taken and multiplied by black rockfish catch in the missing vermilion years to construct alternative catch histories. These two catch histories built with extremes in the vermilion:black rockfish ratio were explored in sensitivity models runs. Lastly, the 1967 value was deemed unrealistc, as it was an order of magnitude higher than reported landings in the 1970s, and it came from a sample of 2 caught fish from Area 2, which is not exptected to contain much vermilion habitat. The extreme expansion of two fish into such a large landings estamate from an area not known for vermilion catch was too suspect to support, so it also became part of the linear interpolaton process described above. A model run with the original 1967 value showed very little sensitivity to this value.

Discard estimates are not available prior to 2002. Based on a discard to retained catch relationship from 2002 to 2020, we estimated historical discards. Discard mortality by depth was applied to post-2001 discards estimate. Prior to 2002, a 32% mortality rate is applied to discarded fish. The sum of retained and dead released `r spp`made up the total removal (in numbers) from the recreational fishery.

#### Lengths
Length compositions for the recreational fleet were available in 1977, 1978, 1980 - 1983, 1986, and then each year from 1993 - 2020 (Table \ref{tab:WA_vermilion_lengthsamples}; Figure \ref{fig:rec-lts_bubbs}). The number of length observations by year were quite variable ranging between 1 and 266 samples per year. Only years with samples sizes >10 were used in the model, as years with low sample sizes can sometimes destabalize models while adding little information.  The size of sexed and unsexed fish observed by the recreational fleet were between 22 and 77 cm. The mean length observed by year was much smaller in early years, but averaged around 45 cm since 1996.

#### Ages
Numbers of collected age structures vary from 3 to 150 per year since 1998, with the majority of the collected age structures coming from 2015 - 2020 (Table \ref{tab:WA_vermilion_agesamples}). No age structures were taken in 2003.  The mean minimum age for all years is 6 with the mean max age being 44.  The average age across all years is 16.  The oldest aged fish in Washington waters is 68 in 1998, but there have been several aged over 50.
