# Assessment Model

## Summary of Previous Assessments 

`r Spp` in Washington has not been previously assessed in full, so this is the first benchmark for this management unit. Depletion-based Stock Reduction Analysis (DBSRA) assuming 40% depletion in 2009 was used to set annual catch limits (ACLs) for `r spp` since 2010 [@dick_estimates_2010]. The total `r spp` OFL in 2011 was 319.5 mt. The mean sustainable yield for the northern portion was estimated to be 11.1 mt, just 3.5% of the total OFL. Most of this allocation would be expected to come from California, as the population of `r spp` continues to be smaller north of California.

### Modelling Platform

Stock Synthesis version 3.30.16 was used as the statistical catch-at-age modelling framework. The SS-DL tool (https://github.com/shcaba/SS-DL-tool) was used for model exploration, likelihood profiling, and sensitivity analyses. The companion R package r4ss (version 1.38.0) along with R version 4.0.5 were used to investigate and plot model fits. 


### Bridging Analysis

No analysis bridging the DBSRA model and Stock Synthesis model was conducted given the significant differences (e.g., DBSRA is provided the relative stock status value) between the methods. It is well documented already that SS can mimic DBSRA approaches [@cope_implementing_2013].


## Model Structure and Assumptions

Stock Synthesis is an age-structured modelling framework that allows for the integration of removal histories, length and age compositions in one model. The Washington `r spp` model assessment assumes one removal fleet (a recreational fishery, thus negligible commerical removals) with removals (in 1000s of fish) beginning in `r startyr`. Selectivity for the fleet were specified using the double normal parameterization within SS where selectivity was fixed to be asymptotic with the ascending slope and size of maximum selectivity parameters estimated. Life history parameters are sex-specific, with one growth type, and assumed stationary. Recruitment assumes a Beverton-Holt stock-recruit relationship and recruitment deviations are estimated.


### Estimated and Fixed Parameters

Natural mortality ($M$) and all growth parameters ($L_{\infty}$, $k$, $t_0$, CV at $t_0$, and CV at $L_{\infty}$) are estimated, as is the two selectivity parameters, the log of the initial recruitment ($logR_0$), and recruitment deviations. Length at maturity, fecundity-weight, and length-weight relationshop, steepness ($h$) and recruitment variance were all fixed. Sensitivity scenarios and likelihood profiles were used to explore uncertainty in the values of the natural mortality and growth parameters. When estimating parameters, the prior for natural mortality was assumed lognormal with a standard deviation of 0.438 (based on the prior developed using the Natural Mortality Tool (see Biology section for more details)); growth parameters were estimated with no priors.


### Data Weighting

Initial sample sizes for the Washington recreational length and age samples were based on the number of fish sampled. The method of Francis [-@francis_data_2011, equation TA1.8] was then used to balance the length and conditional age-at-length composition data among other inputs and likelihood components. The Francis method treats mean length and age as indices, with effective sample size defining the variance around the mean. If the variability around the mean does not encompass model predictions, the data should be down-weighted until predictions fit within the intervals. This method accounts for correlation in the data (i.e., the multinomial distribution), but can be sensitive to years that are outliers, as the amount of down-weighting is applied to all years within a data source, and are not year-specific. Sensitivities were performed examining different data-weighting treatments: 1) the Dirichlet-Multinomial approach [@thorson_model-based_2017], 2) the McAllister-Ianelli Harmonic Mean approach [@mcallister_bayesian_1997], or 3) no data-weighting of lengths.



## Model Selection and Evaluation

The base assessment model for Washington `r spp` was developed to balance parsimony and realism, and the goal was to estimate a spawning output trajectory and realtive stock status for the population of `r spp` in state and federal waters off Washington. The model contains many assumptions to achieve parsimony and uses different data types and sources to estimate reality. A series of investigative model runs were done to achieve the final base model. These include considerations of model structure, data and parameter treatment, estimation phasing, and jittered starting values to achieve a converged and balanced model that provides sensible parameter estimates and derived quantities.

