## Reference Model Diagnostics and Results

### Model Convergence and Acceptability

While there is no definitive measure of model convergence, several measures are routinely applied. These criteria include a low maximum gradient (`r model$maximum_gradient_component`), inversion of the Hessian (passed), reasonable parameter values (passed), and acceptable fits to data (passed). 

An extra effort was given to ensure the model did not rest on a local likelihood minimum. This was done by starting the minimization process from dispersed parameter values away from the maximum likelihood estimates to determine if the approach found a better model fit (i.e., minimum negative log-likelihood value). Starting parameters used a jitter shift value of 0.001. This was repeated 100 times with 30 out of 100 runs returned to the reference model likelihood (Figure \ref{fig:jitter_001}). A better fit, lower negative log-likelihood model was not found in any of the remaining 91 runs. The model did not experience convergence issues when provided reasonable starting values. Through the jittering and likelihood profiles, the present reference model represents the best fit to the data given the assumptions made. 


#### Fits to the Data
##### Lengths
Fits to the length data are examined based on the Pearson residuals-at-length, the annual mean lengths, and aggregated length composition data. Model fits to the annual length composition are shown in [Appendix A](#app_a). Lengths are generally sampled better after year 2014, but the overall samples are generally low (e.g., only 3 years have a total sample size > 100).

Pearson residuals of fits to the length data are generally low with no distinct pattern of misfitting despite lower sample sizes (Figure \ref{fig:rec-pearson}). Fits to the mean lengths, assuming Francis data-weighting, show decreasing female and males lengths after 1999, with a very small increase in mean lengths after 2008, though the overall trend is fairly stable (Figure \ref{fig:rec-mean-len-fit}). Aggregate fits over years are shown in Figure \ref{fig:agg-len-fit}.  Given the small sample sizes, the model fits the aggregate lengths adequately.


##### Conditional Age at Length
Fits to the conditioanl age at length data are examined based on the age-at-length Pearson residuals, the annual mean ages, and mean age at length by year for the recreational fleet samples. The maximum size of the Pearson residuals was large (maximum = 15.95; [Appendix B](#app_b)), though these large residuals were not common. Most of the residuals were small and unnoteworthy and demonstrate the expected shape of the growth curve. As with the lengths, the mean age by year decreased after 1999 then leveled off and gradually increased from 2009 onward (Figure \ref{fig:rec-mean-caal}). Mean ages were generally between 15 year and 20 years old. Fits to the mean ages by length bins show acceptable fits consistent with model expectations [Appendix C](#app_c).


### Reference Model Outputs 
#### Parameter Estimates
A total of fifteen primary parameters were estimated, along with seventy-two recruitment deviations. The reference model parameter estimates along with asymptotic standard errors are shown in Table \ref{tab:model-param} and the likelihood components are shown in Table \ref{tab:likes}. Estimates of derived reference points and approximate 95 percent asymptotic confidence intervals are provided in Table \ref{tab:referenceES}. The low sample sizes, but consistent signal in the data sets, along with so many estimated parameters allows the model to incorporate a large amount of variance in the derived outputs.

The natural mortality for females and males was estimated at `r round(model$parameters[model$parameters$Label == "NatM_p_1_Fem_GP_1", 3],3)` and `r round(model$parameters[model$parameters$Label == "NatM_p_1_Mal_GP_1", 3],3)` yr^-1^, respectively. These values are below the mean prior value, but not unreasonable given the corresponding longevities would be between 62 and 64 years old and the sampled maximum age of 68 came from a fished population.

The estimates of sex-specific growth parameters showed some differences from the externally estimated starting values (Table \ref{tab:model-param} and Figure \ref{fig:len-age-ss}). While $L_{\infty}$ was similar to the external estimates, the model estimated $k$ for female and male fish were lower than the values estimated externally (`r round(model$parameters[model$parameters$Label == "VonBert_K_Fem_GP_1", 3],3)`  for females and `r round(model$parameters[model$parameters$Label == "VonBert_K_Fem_GP_1", 3]*exp(model$parameters[model$parameters$Label == "VonBert_K_Mal_GP_1", 3]),3)` yr^-1^ for males).  The majority of female and male `r spp` growth occurs at younger ages, reaching near maximum length by age 30-40, depending upon sex, with female `r spp` reaching larger maximum lengths (Figure \ref{fig:len-age-ss}). The $t_0$ values (female = `r round(model$Growth_Parameters$A_a_L0[1],3)`; male = `r round(model$Growth_Parameters$A_a_L0[2],3)` were more biologically reasonable than the external estimates using the Washington data.

The estimated logistic selectivity curve for the recreational fishery look plausible (i.e., as a model convergence check for realism, the selectivity curve is not overtly outrageous; Figure \ref{fig:fleet_selectivity}). Length at 50% selectivity (`r round(model$parameters[model$parameters$Label == "Size_DblN_peak_Fishery(1)", 3],3)` cm) was between the length at 50% (39.4 cm) and 95% maturity (48 cm).

The time series of estimated recruitments and annual recruitment deviations are shown in Figures \ref{fig:recruits} and \ref{fig:rec-devs}. Recruitment strengths were generally low; years with the highest recruitment deviations were estimated to have occurred in 1995, 1996, 1999, 2000, 2006, and 2011. All recruitment deviations after 2011 are negative.
The variance check on the recruitment deviations indicates weakly informed recruitments. Recruitment deviations after 2015 are relatively uninformed with estimated deviations near zero where recruitment is estimated primarily based on the spawner-recruit curve (Figure \ref{fig:bh-curve}). The recruitment bias adjustment applied within the model across years is shown in Figure \ref{fig:bias-adj}.


#### Population Trajectory

The predicted spawning output (in millions of eggs) is provided in Table \ref{tab:timeseries} and plotted in Figure \ref{fig:ssb}. Estimated spawning output shows a large decline starting after 1980, with a leveling off of the population after 2000. This tracks the time period of major removals, though removals have stayed somewhat elevated in recent years, bouyed by small but positive recruitments. A decline since 2019 is due to the largest catch on record in 2019 (almost twice the previous largest catch). The estimate of total biomass over time, which tracks that of spawning output, is shown in Figure \ref{fig:tot-bio}. Numbers of age-0 individuals indcate years of above average recruitment (Figure \ref{fig:recruits}).

Median relative spawning output has never declined below the management target ($SB_{40\%}$), and has hovered near 60% for the past 20 years (Figure \ref{fig:depl}). The relative stock status at the start of `r endyr + 1` is estimated to be well above the rockfish relative biomass target of 0.4 (`r round(model$derived_quants[model$derived_quants$Label == 'Bratio_2021','Value'], 2)`). Uncertainty intervals are extremely wide (from near extinct to unfished) given the number of estimated parameters, indicating an overall weakness in the data to firmly inform relative stock status. 
