## Management 

### Reference Points

Reference points were calculated using the estimated fishery selectivity and removals in the most recent year of the model (`r endyr`, Table \ref{tab:referenceES}). Sustainable total yields  were `r round(model$derived_quants[model$derived_quants$Label == 'Dead_Catch_SPR', 'Value'], 2)` mt when using an $SPR_{50\%}$ reference harvest rate. The spawning output equivalent to 40 percent of the unfished spawning output ($SB_{40\%}$) was `r round(model$derived_quants[model$derived_quants$Label == 'SSB_SPR', 'Value'], 2)` meggs. 

The `r endyr + 1` spawning output relative to unfished equilibrium spawning output is above the `r spp` relative biomass target of 40 percent (Figure \ref{fig:depl}). The fishing intensity, $1-SPR$, of recent years was near or above the harvest rate limit ($SPR_{50\%}$) in the early 1990s and late 2010s. Recent years also show near target fishing levels (Table \ref{tab:timeseries} and Figure \ref{fig:1-spr}). Table \ref{tab:referenceES} shows the full suite of estimated reference points for the base model and Figure \ref{fig:yield} shows the equilibrium curve based on a steepness value fixed at `r round(model$parameters[model$parameters$Label == "SR_BH_steep","Value"], 2)`.

### Unresolved Problems and Major Uncertainties
This assessment, while having multiple years of length and age data, has low annual samples sizes for each data source. The growth estimates seem reasonable and do not tend to add a large amount of variability to the model outputs, as the major source of uncertainty stems from the uncertainty in natural mortality. This uncertainty seems larger than even among model uncertainty in the treatments of data or alternative model specifications. The ability to decrease the uncertainty in this parameter would then bring attention back to alternative model specifications. 

The structure of this model is simple-- one non-target fleet with stationary productivity and selectivity and stochastic recruitment allowing non-deterministic changes to the population, yet there is an observable retrospective pattern. This would suggest some sort of bias in the data and/or model misspecification. The limited data and simple models structure makes the latter difficult to explore. It may also be inherent in the fact that this is a small population sensitive to perturbations. Attention to this restrospective pattern should be maintained in future assessments as data increases.

The large ageing error seen in the CARE exchange was untenable for use in a reference model, but should be revisited with further exchanges to figure out why the Washington state ageing was such an outlier to the other laboratories. Further work on the age and growth of `r spp` in Washington would help improve the ageing error and overall growth estimates, and the collection of small individuals would be particularly helpful.

The historical catch history is roughly estimated, though little additional information is avialble to improve this estimate. While this history is very uncertain, the catch level is so small compared to the contemporary catch and overall population that it makes little difference in model results, but remains an area of uncertainty.

### Harvest Projections and Decision Tables

A ten year (2023-2032) projection of the reference model with removals in 2021 and 2022 provided by the Groundfish Management Team for each fleet under the category 2 (sigma=1.0) time-varying buffer using $P^*$ = 0.45 and 40-10 ABC control rule is provided in Table \ref{tab:project}.

The decision table (Table \ref{tab:dec-tab}) was constructed using female and male natural mortality to define the low and high states of nature. The multi-parameter likelihood profile was used to find the low (Female M = 0.07092; Male M= 0.06525) and high (Female M = 0.08527; Male M = 0.07845) female and male natural mortality values that produce -log likeliehood values  +0.66 units from the reference -log likelihood value. These correspond to the 12.5% and 87.5% quantiles (standard quantiles used in west coast decision tables). The catch rows in the table were based on three proposed catch streams:
  1. P* = 0.45, sigma = 0.5
  2. P* = 0.40, sigma = 0.5
  3. An equilibrium catch based on the $F_{MSY}$ proxy using SPR = 1.0  

Catch is modelled as numbers in the assessment, which necessitated conversion of biomass based estimates into numbers for projections. This means that while biomass-based catch streams within each row are static, the numbers associated with those biomass estimates change across the states of nature given age and length structures of varying among states of nature. This requires conversion of biomass to numbers in every year of all low and high states of nature in order to maintain the biomass estimates at expected values. A check was made for each scenario of the decision table to make sure inputted removals in numbers match the expected removals in biomass.

The fixed values for 2021-2022 are very high catches compared to the historical take of vermilion rockfish in Washington state. This has a notable effect on the stock size and status of the low $M$ state of nature. While the reference and high state of nature runs keeps the population near or well above the target stock status for all catch streams, the low state of nature falls well below the overfished limit. The catch streams also show a large drop in catch after the fixed values of 2021-2022, highlighting how each catch control rule will lead to large reductions in future vermilion catch.

### Evaluation of Scientific Uncertainty

The estimated uncertainty in the base model around the `r endyr + 1` spawning output is $\sigma$ = `r round(model$Pstar_sigma,2)` and the uncertainty in the base model around the `r endyr + 1` OFL is $\sigma$ = `r round(model$OFL_sigma,2)`. The large uncertainty aligns with a category 2 level of uncertainty, though the estimated model uncertainty was less than the category 2 groundfish data moderate assessment default value of  $\sigma$ = 1.0. The reasons for designating this a category 2 stock (high estimated model uncertainty) was different than the category 2 California models that were based heavily on the mix of sunset and vermilion rockfishes.

## Research and Data Needs

1. Resolution in stock structure. The Washington population of vermilion rockfish seems to have a large degree of separation from the core population and even the main population found in Oregon. Washington state has begun sampling tissue from landed vermilion rockfish in order to add more resolution to the genetic relatedness among vermilion found in U.S. waters. 
2. The degree of ageing error between otoliths read in the Washington Department of Fish and Wildlife agein lab and others in the CARE exchange highlights the need for further exchanges to determine why these differences exist, as they do not within the WDFW ageing lab, nor among the reads from the other labs. The CARE exchange has high value in general to further our ability to understand the inherent variability of reading ageing structures, and should be strongly supported.
3. The life history parameters are all assumed constant through time. This assumption of stationarity is one of convenience and parsimony. Any insight into the changing of life history values or differing productivity regimes could help refine these assumptions.
4. Natural mortality proved the source of greatest uncertainty in the model. While empirical methods can help define priors for natural mortality, good sampling of age structure or direct measures (e.g., tagging) are preferred. While the small size and rare occurrence of vermilion rockfish off Washington state makes these direct methods a challenge to do, improved data collection may help with natural mortality estimation and reduce model uncertainty.
5. Sample sizes for biological data are small in this assessment, so increases in samples could help reduce model uncertainty. The practicality of this suggestion is questionable as the limited number of `r spp` encountered makes it difficult to increase sample sizes.
6. A fishery-independent index of abundance would be a welcome inclusion in this assessment. Again, such a rarely encountered fish may be hard to monitor via an index of abundance, but the possibility of a nearshore/shallow shelf survey is welcome.
7. The large uncertainty estimated in this stock assessment was limited given the asymptotic, symmetric variance estimation from the maximum likelihood estimation method. While a Bayesian model was considered and even explored for this model, it was not included due to challenges in implementation and lack of enough time to achieve a converged model. Continuted development of Bayesian approaches to characterizing uncertainty are strongly encouraged.
8. Ensemble modelling may be another potential tool to incorporate model uncertainty beyond within model variance estimation that should be considered.
9. Fishery selectivity continues to be challenging to represent, and are key parameters in the model. Blocks in selectivity and whether there are $a priori$ reasons to expect any dome-shaped selectivity deserve continued thought, though again it is especially challenging given the rarity of occurrence and non-target nature of vermilion rockfish.
