\clearpage
# Figures

<!-- ====================================================================== --> 
<!-- ******************************* ES *********************************** --> 
<!-- ====================================================================== --> 


<!-- ====================================================================== --> 
<!-- ******************* Intro section *************************** --> 
<!-- ====================================================================== --> 

```{r, results = 'asis'}
add_figure(
filein = file.path(stock_fig_loc, "Vermilion_Map.png"), 
caption = "Oregon and Washington coastlines with rocky habitat indicated by brown shaded areas. Circled areas represent areas of primary vermilion rockfish occurence",
label = 'ORWA-map')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(stock_fig_loc, "TM_Vermilion_ORWA.png"), 
caption = "Total mortality from the southern Oregon and northern Washington recreational fisheries. These represent ninety and ninety-seven percent of the total vermilion rockfish removals in each state, respectively",
label = 'tm-plot')
```


<!-- ====================================================================== --> 
<!-- ******************* Data Used in the Model *************************** --> 
<!-- ====================================================================== --> 

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "data_plot.png"), 
caption = "Summary of data sources used in the reference model",
label = 'data-plot')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(bio_fig_loc, "WA_black_vermilion.png"), 
caption = "Plot of year to the vermilion:black rockfish (V_B) landing ratio. The linear model presented was used to predict vermilion rockfish catch from black rockfish catch for years of missing vermilion rockfish landings. The linear (y=ax+b) coefficients were a= 0.000016 and b= 0.029710",
label = 'WA_black_vermilion')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat__multi-fleet_comparison.png"), 
caption = "Bubble plot of length compositions by year. Size of the bubble indicates higher proportion. All proportions within year sum to one",
label = 'rec-lts_bubbs')
```


<!-- ====================================================================== --> 
<!-- ******************* Data Used in the Model *************************** --> 
<!-- ====================================================================== --> 


<!-- ====================================================================== -->
<!-- *************************     Biology     **************************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(bio_fig_loc, "AG_plot_lines_parameters.png"), 
caption = "Observed length-at-age by data source and sex. Lines indicate fits to the von Bertalanffy growth equation, with initial parameter estimates provided in the bottom right corner of the figure",
label = 'len-age-data')
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bio1_sizeatage.png"), 
caption = "Model estimated length-at-age in the beginning of the year. Shaded area indicates 95 percent distribution of length-at-age around the estimated growth curve",
label = 'len-age-ss')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(bio_fig_loc, "Age_error_plot.png"), 
caption = "Ageing error matrix (age by standard deviation (SD)) values by source. The recreational matrix is based on intra-reader comparisons",
label = 'age-error')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bio6_maturity.png"), 
caption = "Maturity as a function of length (cm)",
label = 'maturity')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bio9_fecundity_len.png"), 
caption = "Fecundity (kg) as a function of length (cm)",
label = 'fecundity')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(bio_fig_loc, "Mdensityplots_OR_vermilion.png"), 
caption = "Composite natural mortality distriubtion for vermilion rockfish using four longevity estimators each with a SD = 0.438 presuming a lognomral error distibution",
label = 'M_composite_dists')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(bio_fig_loc, "Vermilion_WA_Lt_Wt.png"), 
caption = "Length (cm)-weight (kg) data and fits to sex-specific vermilion rockfish samples from the recreational fishery",
label = 'len-weight-fit')
```


<!-- ====================================================================== -->
<!-- *********************    Selectivity            ********************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "/plots"), "sel01_multiple_fleets_length1.png"), 
caption = "Selectivity at length (cm) by fleet",
label = 'selex')
```


<!-- ====================================================================== -->
<!-- ***********************  Jitters  ************************************ --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "Jitter Results", "jitterplot_001.png"), 
caption = "Jitter runs for the vermilion rockfish reference model, with jitter run number on the x-axis and -log likelihood value on the y-axis. Blue dot are models that match the likelihood value of the reference model, while red dots deviate from the reference model. All red dots are above the blue dots, indicating no better fit to the reference model was found",
label = 'jitter_001')
```


<!-- ====================================================================== -->
<!-- ****************** Fit to the Length Data **************************** --> 
<!-- ====================================================================== -->


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit__multi-fleet_comparison.png"), 
caption = "Pearson residuals for the recreational fleet. Closed bubble are positive residuals (observed > expected) and open bubbles are negative residuals (observed < expected)",
label = 'rec-pearson')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_data_weighting_TA1.8_Fishery.png"), 
caption = "Mean length (cm) index from the recreational fishery with 95 percent confidence intervals based on sample sizes and data weighting",
label = 'rec-mean-len-fit')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit__aggregated_across_time.png"), 
caption = "Aggregated length (cm) compositions over all years",
label = 'agg-len-fit')
```


<!-- ====================================================================== -->
<!-- ****************** Fit to the Age Data ******************************* --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_condAALfit_data_weighting_TA1.8_condAgeFishery.png"), 
caption = "Mean age observations from the conditional age-at-length (cm) data from the recreational fishery",
label = 'rec-mean-caal')
```


<!-- ====================================================================== -->
<!-- ************************* Selectivity ******************************** --> 
<!-- ====================================================================== -->


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "sel01_multiple_fleets_length1.png"),
caption = "Length-based selectivity curves for the commercial and recreational fisheries",
label = 'fleet_selectivity')
```


<!-- ======================================================= -->  
<!-- ****************** Time Series ************************ --> 
<!-- ======================================================= -->


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts7_Spawning_output_with_95_asymptotic_intervals_intervals.png"), 
caption = "Estimated time series of spawning output (in millions of eggs). Values at or less than zero are not realistic and result from the normality assumption of the asymptotic variance estimation",
label = 'ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts1_Total_biomass_(mt).png"), 
caption = "Estimated time series of total biomass (mt)",
label = 'tot-bio')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts9_Relative_spawning_output_intervals.png"), 
caption = "Estimated time series of fraction of unfished spawning output",
label = 'depl')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts11_Age-0_recruits_(1000s)_with_95_asymptotic_intervals.png"), 
caption = "Estimated time series of age-0 recruits (1000s)",
label = 'recruits')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "recdevs2_withbars.png"), 
caption = "Estimated time series of recruitment deviations",
label = 'rec-devs')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "recdevs3_varcheck.png"), 
caption = "Recruitment deviations variance by year. This plot tracks the information content contained in each recruitment deviation. Values below the red line (assumed recruitment variability) indicates years with more informed recruitment deviations",
label = 'rec-devs-sigmas')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "SR_curve.png"), 
caption = "Stock-recruit curve. Point colors indicate year, with warmer colors indicating earlier years and cooler colors in showing later years",
label = 'bh-curve')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "recruit_fit_bias_adjust.png"),
caption = "Recruitment bias adjustment applied in the reference model",
label = 'bias-adj')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "SR_curve.png"), 
caption = "Stock recruit curve where point color indicates year, with warmer colors (yellow to green) indicating earlier years and cooler colors (blue) showing later years",
label = 'sr-curve')
```


<!-- ====================================================================== -->
<!-- ******************       Sensitivity     ***************************** --> 
<!-- ====================================================================== -->

```{r, echo=FALSE, results='asis'}
add_figure(
filein = file.path(sensi_data_fig_loc, "Sensi_logREplot_SB_Dep_F_MSY.png"),
caption = "Log relative change (log((Model_sensi-Model_ref)/Model_ref)) in data treatment for 5 derived quantities. Colored boxes indicate 95 percent confidence interval of the reference model",
label = 'sensi-data-RE')
```

```{r, echo=FALSE, results='asis'}
add_figure(
filein = file.path(sensi_data_fig_loc, "compare2_spawnbio_uncertainty.png"),
caption = "Spawning output (in millions of eggs) time series by data treatment compared to the reference model. Missing scenarios mean the spawning output was too large to show",
label = 'sensi-data-ssb')
```

```{r, echo=FALSE, results='asis'}
add_figure(
filein = file.path(sensi_data_fig_loc, "compare4_Bratio_uncertainty.png"),
caption = "Relative spawning output time series by data treatment compared to the reference model",
label = 'sensi-data-depl')
```

```{r, echo=FALSE, results='asis'}
add_figure(
filein = file.path(sensi_modspex_fig_loc, "Sensi_logREplot_SB_Dep_F_MSY.png"),
caption = "Log relative change (log((Model_sensi-Model_ref)/Model_ref)) in model specification scenario for 5 derived quantities. Colored boxes indicate 95 percent confidence interval of the reference model",
label = 'sensi-modspec-RE')
```

```{r, echo=FALSE, results='asis'}
add_figure(
filein = file.path(sensi_modspex_fig_loc, "compare2_spawnbio_uncertainty.png"),
caption = "Spawning output (in millions of eggs) time series by model specification scenario compared to the reference model. Missing scenarios mean the spawning output was too large to show",
label = 'sensi-modspec-ssb')
```

```{r, echo=FALSE, results='asis'}
add_figure(
filein = file.path(sensi_modspex_fig_loc, "compare4_Bratio_uncertainty.png"),
caption = "Relative spawning output time series by model specification scenario compared to the reference model",
label = 'sensi-modspec-depl')
```


<!-- ============================================================================== -->
<!-- ******************      Likelihood Profiles      ***************************** --> 
<!-- ============================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(likeprof_fig_loc,"Profile_plots_R0.png"), 
caption = "$Ln(R0)$ likelihood profile (change in the negative log-likelihood across a range of $ln(R0)$ values) and derived quantities (left four figures) and likelihood component contributions (right three figures). Red line in the top left most figure indicates the significance level in likelihood difference",
label = 'r0-profile-combo')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(likeprof_fig_loc,"Profile_plots_h.png"), 
caption = "Steepness likelihood profile (change in the negative log-likelihood across a range of steepness values) and derived quantities (left four figures) and likelihood component contributions (right three figures)",
label = 'steepness-profile-combo')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(likeprof_fig_loc,"Profile_plots_M_f.png"), 
caption = "Female $M$ likelihood profile (change in the negative log-likelihood across a range of $M$ values) and derived quantities (left four figures) and likelihood component contributions (right three figures)",
label = 'M_f-profile-combo')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(likeprof_fig_loc, "Profile_plots_M_m.png"), 
caption = "Male $M$ likelihood profile (change in the negative log-likelihood across a range of $M$ values) and derived quantities (left four figures) and likelihood component contributions (right three figures)",
label = 'M_m-profile-combo')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(likeprof_fig_loc, "multilikelihood_profile_M_f_m.png"), 
caption = "Female and male $M$ multi-parameter likelihood profile and derived quantities. Red lines in the top left figure indicate significantly similar values compared to the reference model. Broken and solid lines in the bottom right figure indicate target and limit referene points, respectively",
label = 'M-multiprofile-combo')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(likeprof_fig_loc, "Assymetric_var_M.png"), 
caption = "Relative stock status time series from the female and male $M$ multi-parameter likelihood profile. Broken lines indicate target and limit reference points",
label = 'M-multiprofile-Bratio')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(likeprof_fig_loc, "Profile_plots_Linf_f.png"), 
caption = "Female $L_{inf}$ likelihood profile (change in the negative log-likelihood across a range of $L_{inf}$ values) and derived quantities (left four figures) and likelihood component contributions (right three figures)",
label = 'Linf_F-profile-combo')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(likeprof_fig_loc,"Profile_plots_k_f.png"), 
caption = "Female $k$ likelihood profile (change in the negative log-likelihood across a range of $k$ values) and derived quantities (left four figures) and likelihood component contributions (right three figures)",
label = 'k_f-profile-combo')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(likeprof_fig_loc,"multilikelihood_profile_F_Linf_k.png"), 
caption = "Female $L_{inf}$ and $k$ multi-parameter likelihood profile and derived quantities. Red lines in the top left figure indicate significantly similar values compared to the reference model. Broken and solid lines in the bottom right figure indicate target and limit referene points, respectively",
label = 'Linf_k_f-profile')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(likeprof_fig_loc,"Profile_plots_CV_f.png"), 
caption = "Female variability at maximum age likelihood profile (change in the negative log-likelihood across a range of CV at maximum age values) and derived quantities (left four figures) and likelihood component contributions (right three figures)",
label = 'CVold_f-profile-combo')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(likeprof_fig_loc,  "Profile_plots_Linf_m.png"), 
caption = "Male $L_{inf}$ likelihood profile (change in the negative log-likelihood across a range of $L_{inf}$ values) and derived quantities (left four figures) and likelihood component contributions (right three figures)",
label = 'Linf_M-profile-combo')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(likeprof_fig_loc,  "Profile_plots_k_m.png"), 
caption = "Male $k$ likelihood profile (change in the negative log-likelihood across a range of $k$ values) and derived quantities (left four figures) and likelihood component contributions (right three figures)",
label = 'k_m-profile-combo')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(likeprof_fig_loc,  "multilikelihood_profile_M_Linf_k.png"), 
caption = "Male $L_{inf}$ and $k$ multi-parameter likelihood profile and derived quantities. Red lines in the top left figure indicate significantly similar values compared to the reference model. Broken and solid lines in the bottom right figure indicate target and limit referene points, respectively",
label = 'Linf_k_m-profile')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(likeprof_fig_loc,  "Profile_plots_CV_m.png"), 
caption = "Male variability at maximum age likelihood profile (change in the negative log-likelihood across a range of CV at maximum age values) and derived quantities (left four figures) and likelihood component contributions (right three figures)",
label = 'CVold_m-profile-combo')
```


<!-- ====================================================================== -->
<!-- ******************     Retrospectives    ***************************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(retro_loc,  "compare2_spawnbio_uncertainty.png"), 
caption = "Change in the estimate of spawning output when the most recent 10 years of data area removed sequentially",
label = 'retro-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(retro_loc,  "compare4_Bratio_uncertainty.png"),
caption = "Change in the estimate of fraction unfished when the most recent 10 years of data area removed sequentially",
label = 'retro-depl')
```

\newpage

<!-- ====================================================================== -->
<!-- ******************    Reference Points    **************************** --> 
<!-- ====================================================================== -->


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "SPR2_minusSPRseries.png"), 
caption = "Estimated 1 - relative spawning ratio (SPR) by year",
label = '1-spr')
```

\clearpage

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "SPR4_phase.png"), 
caption = "Phase plot of the relative biomass (also referred to as fraction unfished) versus the SPR ratio where each point represents the biomass ratio at the start of the year and the relative fishing intensity in that same year. Lines through the final point show the 95 percent intervals based on the asymptotic uncertainty for each dimension. The shaded ellipse is a 95 percent region which accounts for the estimated correlations between the biomass ratio and SPR ratio",
label = 'phase')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "yield2_yield_curve_with_refpoints.png"), 
caption = "Equilibrium yield curve for the reference model. Values are based on the 2020
fishery selectivities and with steepness fixed at 0.72",
label = 'yield')
```

